version: "2"
linters:
  enable:
    - exhaustive
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - golines
  settings:
    gofumpt:
      extra-rules: true
    golines:
      max-len: 100
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
